const els={name:document.querySelector('#instructor-name'),loading:document.querySelector('#loading-message'),form:document.querySelector('#session-form'),notice:document.querySelector('#notice'),template:document.querySelector('#training-template'),date:document.querySelector('#training-date'),comment:document.querySelector('#common-comment'),templateInfo:document.querySelector('#template-info'),search:document.querySelector('#agent-search'),rank:document.querySelector('#rank-filter'),list:document.querySelector('#agents-list'),empty:document.querySelector('#agents-empty'),selectedCount:document.querySelector('#selected-count'),summary:document.querySelector('#submit-summary'),save:document.querySelector('#save-session'),selectVisible:document.querySelector('#select-visible'),clear:document.querySelector('#clear-selection'),historyPanel:document.querySelector('#history-panel'),history:document.querySelector('#history-list'),historyEmpty:document.querySelector('#history-empty'),refresh:document.querySelector('#refresh-history')};
const resultLabels={planifiee:'Planifiée',valide:'Validée',a_revoir:'À revoir',non_valide:'Non validée'};let agents=[],templates=[],selected=new Map();
const esc=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(response.status===401){location.replace('/academy-auth/login.html?error=login_required');throw new Error('unauthorized')}if(!response.ok||!data.ok)throw new Error(data.code||'request_failed');return data}
function showNotice(text,type='success'){els.notice.textContent=text;els.notice.className=`notice ${type}`;els.notice.hidden=false;scrollTo({top:0,behavior:'smooth'})}
function filteredAgents(){const q=els.search.value.trim().toLocaleLowerCase('fr');return agents.filter(a=>(!els.rank.value||a.rank===els.rank.value)&&(!q||`${a.displayName} ${a.rpName} ${a.matricule} ${a.rank}`.toLocaleLowerCase('fr').includes(q)))}
function defaultParticipant(id){return {discordId:id,result:'planifiee',score:'',note:''}}
function updateSummary(){const count=selected.size;els.selectedCount.textContent=String(count);els.selectedCount.nextElementSibling.textContent=`participant${count>1?'s':''} sélectionné${count>1?'s':''}`;els.summary.textContent=count<2?'Sélectionnez au moins 2 participants':`${count} participants à enregistrer`;els.save.disabled=count<2||!els.template.value||!els.date.value}
function renderAgents(){const filtered=filteredAgents();els.empty.hidden=Boolean(filtered.length);els.list.innerHTML=filtered.map(agent=>{const value=selected.get(agent.discordId)||defaultParticipant(agent.discordId);const checked=selected.has(agent.discordId);return `<article class="agent-row${checked?' selected':''}" data-id="${agent.discordId}"><input class="agent-check" type="checkbox" ${checked?'checked':''} aria-label="Sélectionner ${esc(agent.displayName)}"><div class="agent-identity"><strong>${esc(agent.rpName||agent.displayName)}</strong><span>${esc(agent.rank)}${agent.matricule?` · ${esc(agent.matricule)}`:''}</span></div><select class="agent-result" aria-label="Résultat"><option value="planifiee" ${value.result==='planifiee'?'selected':''}>Planifiée</option><option value="valide" ${value.result==='valide'?'selected':''}>Validée</option><option value="a_revoir" ${value.result==='a_revoir'?'selected':''}>À revoir</option><option value="non_valide" ${value.result==='non_valide'?'selected':''}>Non validée</option></select><input class="agent-score" type="number" min="0" max="100" value="${esc(value.score)}" placeholder="Score" aria-label="Score sur 100"><input class="agent-note" maxlength="900" value="${esc(value.note)}" placeholder="Note individuelle…" aria-label="Note individuelle"></article>`}).join('');updateSummary()}
function saveRow(row){const id=row.dataset.id;if(!selected.has(id))return;selected.set(id,{discordId:id,result:row.querySelector('.agent-result').value,score:row.querySelector('.agent-score').value,note:row.querySelector('.agent-note').value.trim()})}
function renderTemplateInfo(){const template=templates.find(item=>item.id===els.template.value);els.templateInfo.hidden=!template;els.templateInfo.innerHTML=template?`<strong>${esc(template.name)}</strong>${esc(template.description||'Formation disponible dans la bibliothèque Academy.')}`:'';updateSummary()}
function formatDate(value){return new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium'}).format(new Date(`${String(value).slice(0,10)}T12:00:00`))}
function renderHistory(sessions){els.historyEmpty.hidden=Boolean(sessions.length);els.history.innerHTML=sessions.map(session=>{const scores=session.participants.filter(p=>Number.isInteger(p.score));const average=scores.length?Math.round(scores.reduce((n,p)=>n+p.score,0)/scores.length):null;return `<article class="history-card"><div><h3>${esc(session.trainingType)}</h3><div class="history-meta"><span>${formatDate(session.trainingDate)}</span><span>${esc(session.instructorName)}</span><span>${session.participantCount} participant${session.participantCount>1?'s':''}</span></div><div class="history-participants">${session.participants.map(p=>`<a href="/academy-admin/dossier.html?id=${encodeURIComponent(p.discordId)}">${esc(p.agentName||p.discordId)} · ${esc(resultLabels[p.result]||p.result)}</a>`).join('')}</div></div><div class="history-score"><strong>${average===null?'—':`${average}%`}</strong><span>moyenne</span></div></article>`}).join('')}
async function loadHistory(){try{const data=await api('/api/academy-admin-data/training-sessions');renderHistory(data.sessions)}catch(error){if(error.message!=='unauthorized'){els.history.innerHTML='<p class="empty">Impossible de charger les sessions récentes.</p>'}}}
async function initialize(){try{const [agentData,templateData]=await Promise.all([api('/api/academy-admin-data/agents'),api('/api/academy-admin-data/training-templates')]);agents=agentData.agents;templates=templateData.templates.filter(t=>t.active);els.name.textContent=agentData.instructor?.globalName||agentData.instructor?.username||'Instructeur';agentData.ranks.forEach(rank=>els.rank.add(new Option(rank,rank)));templates.forEach(t=>els.template.add(new Option(t.name,t.id)));els.date.valueAsDate=new Date();els.loading.hidden=true;els.form.hidden=false;els.historyPanel.hidden=false;renderAgents();await loadHistory()}catch(error){if(error.message!=='unauthorized')els.loading.textContent='Impossible de charger les données de la session.'}}
els.list.addEventListener('change',event=>{const row=event.target.closest('.agent-row');if(!row)return;const id=row.dataset.id;if(event.target.classList.contains('agent-check')){if(event.target.checked)selected.set(id,defaultParticipant(id));else selected.delete(id);renderAgents()}else saveRow(row);updateSummary()});
els.list.addEventListener('input',event=>{const row=event.target.closest('.agent-row');if(row)saveRow(row)});els.search.addEventListener('input',renderAgents);els.rank.addEventListener('change',renderAgents);els.template.addEventListener('change',renderTemplateInfo);els.date.addEventListener('change',updateSummary);
els.selectVisible.addEventListener('click',()=>{filteredAgents().forEach(a=>{if(!selected.has(a.discordId))selected.set(a.discordId,defaultParticipant(a.discordId))});renderAgents()});els.clear.addEventListener('click',()=>{selected.clear();renderAgents()});els.refresh.addEventListener('click',loadHistory);
els.form.addEventListener('submit',async event=>{event.preventDefault();document.querySelectorAll('.agent-row').forEach(saveRow);if(!selected.size)return;els.save.disabled=true;els.save.textContent='Enregistrement…';try{const data=await api('/api/academy-admin-data/training-session/create',{method:'POST',body:JSON.stringify({templateId:els.template.value,trainingDate:els.date.value,commonComment:els.comment.value.trim(),participants:[...selected.values()]})});showNotice(`Session enregistrée dans ${data.createdCount} dossier${data.createdCount>1?'s':''}.`);selected.clear();els.comment.value='';renderAgents();await loadHistory()}catch(error){showNotice(error.message==='invalid_training_session'?'Vérifiez la formation, la date et les résultats.':'Impossible d’enregistrer toute la session. Aucun nouveau dossier ne doit être ajouté avant vérification.','error')}finally{els.save.textContent='Enregistrer la session';updateSummary()}});initialize();
