(()=>{
 const form=document.getElementById('complaint-form'),button=document.getElementById('submit-complaint'),status=document.getElementById('complaint-status'),description=document.getElementById('complaint-description'),counter=document.getElementById('description-count');
 const setStatus=(message,type)=>{status.hidden=false;status.className=`status ${type||''}`;status.innerHTML=message};
 const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const updateCount=()=>{counter.textContent=`${description.value.length} / 5000`}; description.addEventListener('input',updateCount);updateCount();
 const date=document.getElementById('complaint-date'); if(date&&!date.value){const now=new Date();now.setMinutes(now.getMinutes()-now.getTimezoneOffset());date.value=now.toISOString().slice(0,16)}
 form.addEventListener('submit',async event=>{event.preventDefault();if(!description.value.trim()){setStatus('La description des faits est obligatoire.','error');description.focus();return}button.disabled=true;setStatus('Transmission du dépôt…');
  const payload=Object.fromEntries(new FormData(form).entries());
  try{const response=await fetch('/api/liaison/complaints',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(response.status===401){location.href='/auth/login.html?error=login_required';return}if(!response.ok)throw new Error(data.code||data.error||'discord_unavailable');
   setStatus(`Dépôt enregistré sous <strong>${escapeHtml(data.complaintId)}</strong>. <a href="${escapeHtml(data.url||'#')}" target="_blank" rel="noopener">Ouvrir le dossier Discord ↗</a>`,'ok');form.reset();updateCount();
  }catch(error){const messages={description_required:'La description des faits est obligatoire.',forum_forbidden:'Le bot Discord n’a pas les droits nécessaires sur le forum.',discord_unavailable:'Discord est momentanément indisponible. Réessayez dans quelques instants.'};setStatus(messages[error.message]||'Impossible d’enregistrer le dépôt. Réessayez.','error')}finally{button.disabled=false}
 });
 const list=document.getElementById('complaint-list'),tabs=[...document.querySelectorAll('[data-tab]')],threads=document.getElementById('threads'),detail=document.getElementById('thread-detail');
 async function loadThreads(){threads.innerHTML='<p>Chargement…</p>';try{const r=await fetch('/api/liaison/complaints',{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.code);threads.innerHTML=(d.threads||[]).map(t=>`<button class="thread-card" data-id="${t.id}"><strong>${escapeHtml(t.name)}</strong><span>${t.archived?'Archivé':'Actif'} · ${(t.tags||[]).map(escapeHtml).join(', ')||'Sans tag'}</span></button>`).join('')||'<p>Aucun dépôt trouvé.</p>';if(d.archiveError)threads.insertAdjacentHTML('afterbegin','<p class="warning">Archives Discord inaccessibles : donne au bot « Voir le salon » et « Lire l’historique des messages ».</p>');threads.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>loadDetail(b.dataset.id))}catch(e){threads.innerHTML=e.message==='forum_read_forbidden'?'<p class="warning">Le bot n’a pas la permission de lire ce forum.</p>':'<p>Impossible de charger les dépôts.</p>'}}
 async function loadDetail(id){detail.hidden=false;detail.innerHTML='<p>Chargement du fil…</p>';const r=await fetch(`/api/liaison/complaints?threadId=${encodeURIComponent(id)}`,{credentials:'same-origin'});const d=await r.json();if(!r.ok){detail.innerHTML='<p>Impossible de charger ce fil.</p>';return}detail.innerHTML=`<h3>${escapeHtml(d.thread?.name||'Dépôt')}</h3>${(d.messages||[]).reverse().map(m=>`<div class="message"><b>${escapeHtml(m.author?.global_name||m.author?.username||'Agent')}</b><small>${escapeHtml(m.timestamp||'')}</small><p>${escapeHtml(m.content||'')}</p></div>`).join('')}`}
 tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.toggle('active',x===t));const isList=t.dataset.tab==='list';form.hidden=isList;list.hidden=!isList;if(isList)loadThreads()});
})();
