(() => {
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const validId = v => /^\d{17,20}$/.test(String(v || "").trim());
  const ids = v => [...new Set(String(v || "").split(/[\s,;]+/).map(x => x.trim()).filter(validId))];
  const iconLabels = {inbox:"Dossier",radio:"Radio",users:"Membres",book:"Document",list:"Liste"};
  let state = {config:null, history:[], administrators:[], catalog:{}, dirty:false};
  function notice(message, error=false){const n=$("#notice");n.textContent=message;n.className=`notice${error?" error":""}`;n.hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>n.hidden=true,7000)}
  function dirty(){state.dirty=true;$("#dirty").textContent="Modifications non publiées"}
  async function json(url, options={}){const r=await fetch(url,{credentials:"same-origin",cache:"no-store",...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.code||`HTTP ${r.status}`);return d}
  function serverOptions(selected){return state.config.servers.map(s=>`<option value="${esc(s.key)}" ${s.key===selected?"selected":""}>${esc(s.label)} · ${esc(s.guildId||"ID manquant")}</option>`).join("")}
  function renderServers(){
    $("#server-list").innerHTML=state.config.servers.map((s,i)=>`<article class="server-card" data-server="${i}"><div class="card-head"><strong>${esc(s.label||"Serveur")}</strong><button class="remove" data-remove-server type="button" ${state.config.servers.length<2?"disabled":""}>Retirer</button></div><div class="field-grid"><label class="field">Nom affiché<input data-f="label" value="${esc(s.label)}" maxlength="80"></label><label class="field">Clé interne<input data-f="key" value="${esc(s.key)}" maxlength="40"></label><label class="field span-2">ID du serveur<input data-f="guildId" value="${esc(s.guildId)}" inputmode="numeric" maxlength="20"></label><label class="switch span-2"><input data-f="enabled" type="checkbox" ${s.enabled?"checked":""}> Serveur actif</label></div></article>`).join("");
  }
  function channelChoices(channel){const cat=state.catalog[channel.guildKey];if(!cat)return `<option value="${esc(channel.channelId)}" selected>${esc(channel.channelId||"Catalogue à charger")}</option>`;return `<option value="">Choisir un salon Discord…</option>`+cat.channels.map(x=>`<option value="${esc(x.id)}" ${x.id===channel.channelId?"selected":""}># ${esc(x.name)} · ${esc(x.category)} · ${x.type==="forum"?"forum":"texte"}</option>`).join("")}
  async function loadCatalog(guildId){if(!guildId)return null;if(state.catalog[guildId])return state.catalog[guildId];const d=await json(`/api/admin/discord-catalog?guildId=${encodeURIComponent(guildId)}`);state.catalog[guildId]=d;return d}
  function renderLiaisons(){
    $("#liaison-list").innerHTML=state.config.liaison.channels.map((c,i)=>`<article class="liaison-card" data-liaison="${i}" data-disabled="${!c.enabled}"><div class="liaison-title"><div><span class="liaison-badge">LIAISON ${String(i+1).padStart(2,"0")}</span><strong>${esc(c.label||"Nouvelle liaison")}</strong><small>${esc(c.channelId||"Aucun salon sélectionné")}</small></div><button class="remove" data-remove-liaison type="button">Supprimer</button></div><div class="liaison-form"><label class="field">Nom dans le MDT<input data-f="label" value="${esc(c.label)}" maxlength="90"></label><label class="field">Clé technique<input data-f="key" value="${esc(c.key)}" maxlength="40"></label><label class="field">Serveur<select data-f="guildKey">${serverOptions(c.guildKey)}</select></label><label class="field">Salon / forum<select data-f="channelId">${channelChoices(c)}</select></label><label class="field">Type<select data-f="type"><option value="text" ${c.type==="text"?"selected":""}>Canal classique</option><option value="forum" ${c.type==="forum"?"selected":""}>Forum</option></select></label><label class="field">Icône<select data-f="icon">${Object.entries(iconLabels).map(([v,l])=>`<option value="${v}" ${c.icon===v?"selected":""}>${l}</option>`).join("")}</select></label><label class="field">Ordre<input data-f="sortOrder" type="number" min="0" max="9999" value="${Number(c.sortOrder)||0}"></label><div class="switches"><label class="switch"><input data-f="enabled" type="checkbox" ${c.enabled?"checked":""}> Visible</label><label class="switch"><input data-f="canRead" type="checkbox" ${c.canRead?"checked":""}> Lecture</label><label class="switch"><input data-f="canWrite" type="checkbox" ${c.canWrite?"checked":""}> Écriture</label><label class="switch"><input data-f="canUpload" type="checkbox" ${c.canUpload?"checked":""}> Fichiers</label><label class="switch"><input data-f="canMention" type="checkbox" ${c.canMention?"checked":""}> Mentions</label></div></div></article>`).join("")||`<p class="empty">Aucune liaison. Ajoute la première rubrique du MDT.</p>`;
  }
  function renderAccess(){
    const names={police:"Connexion policier",academy:"Police Academy",admin:"Accès technique (secours)"};
    $("#access-list").innerHTML=Object.entries(state.config.access).map(([key,a])=>`<article class="access-card" data-access="${key}"><h3>${names[key]||esc(a.label)}</h3><div class="field-grid"><label class="field">Serveur contrôlé<select data-f="guildKey">${serverOptions(a.guildKey)}</select></label><label class="field">Condition<select data-f="mode"><option value="any" ${a.mode!=="all"?"selected":""}>Au moins un rôle</option><option value="all" ${a.mode==="all"?"selected":""}>Tous les rôles</option></select></label><label class="field span-2">Rôles autorisés<textarea data-f="roleIds" placeholder="Un ID par ligne">${esc((a.roleIds||[]).join("\n"))}</textarea></label><label class="field span-2">IDs autorisés individuellement<textarea data-f="userIds" placeholder="Un ID par ligne">${esc((a.userIds||[]).join("\n"))}</textarea></label><div class="span-2"><button class="button" data-load-roles type="button">Charger les rôles du serveur</button><div class="role-picker" data-role-picker></div></div></div></article>`).join("");
  }
  function renderAdmins(){
    $("#admin-list").innerHTML=state.administrators.map(a=>`<div class="admin-row"><div><strong>${esc(a.displayName||a.discordId)}</strong><small>${esc(a.discordId)}${a.owner?" · propriétaire":" · accès ajouté depuis le panel"}</small></div>${a.owner?'<span class="owner-label">PROPRIÉTAIRE</span>':`<button class="remove" data-remove-admin="${esc(a.discordId)}" type="button">Révoquer</button>`}</div>`).join("")||'<p class="empty">Aucun administrateur supplémentaire.</p>'}
  function renderHistory(){$("#history-list").innerHTML=state.history.length?state.history.map(h=>`<div class="history-row"><div><strong>Version ${h.version}</strong><small>${esc(h.summary||"Modification")} · ${esc(h.changedByName||"Système")} · ${new Date(h.createdAt).toLocaleString("fr-FR")}</small></div><button class="button" data-restore="${esc(h.id)}" type="button">Restaurer</button></div>`).join(""):'<p class="empty">Aucune ancienne version.</p>'}
  function renderMeta(d){$("#version").textContent=d.meta?.version??"—";$("#stat-version").textContent=d.meta?.version??"—";$("#updated").textContent=d.meta?.updatedAt?`${d.meta.updatedByName||"Administrateur"} · ${new Date(d.meta.updatedAt).toLocaleString("fr-FR")}`:"Configuration initiale";$("#actor-name").textContent=d.user?.displayName||"Administrateur";$("#stat-servers").textContent=state.config.servers.length;$("#stat-liaisons").textContent=state.config.liaison.channels.filter(x=>x.enabled).length;$("#stat-admins").textContent=state.administrators.length}
  function render(){renderServers();$("#section-label").value=state.config.liaison.sectionLabel||"Liaison gouvernement";renderLiaisons();renderAccess();renderAdmins();renderHistory();renderMeta({meta:state.meta,user:state.user});$("#dirty").textContent="Aucune modification en attente";state.dirty=false}
  function collect(){
    const servers=$$("[data-server]").map(card=>({key:card.querySelector('[data-f="key"]').value,label:card.querySelector('[data-f="label"]').value,guildId:card.querySelector('[data-f="guildId"]').value,enabled:card.querySelector('[data-f="enabled"]').checked}));
    const channels=$$("[data-liaison]").map(card=>{const f=n=>card.querySelector(`[data-f="${n}"]`);return {key:f("key").value,label:f("label").value,channelId:f("channelId").value,guildKey:f("guildKey").value,type:f("type").value,icon:f("icon").value,sortOrder:Number(f("sortOrder").value)||0,enabled:f("enabled").checked,canRead:f("canRead").checked,canWrite:f("canWrite").checked,canUpload:f("canUpload").checked,canMention:f("canMention").checked}});
    const access={};$$('[data-access]').forEach(card=>{const f=n=>card.querySelector(`[data-f="${n}"]`);access[card.dataset.access]={label:state.config.access[card.dataset.access].label,guildKey:f("guildKey").value,mode:f("mode").value,roleIds:ids(f("roleIds").value),userIds:ids(f("userIds").value)}});
    return {servers,access,liaison:{sectionLabel:$("#section-label").value,channels}};
  }
  async function load(){const d=await json("/api/admin/configuration");state={...state,config:d.config,history:d.history||[],administrators:d.administrators||[],meta:d.meta,user:d.user};await Promise.all(state.config.servers.filter(s=>s.guildId).map(s=>loadCatalog(s.guildId).catch(()=>null)));render()}
  async function save(){try{await json("/api/admin/configuration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"save",config:collect(),summary:$("#summary").value})});$("#summary").value="";notice("Configuration publiée. Les nouveaux réglages sont actifs.");await load()}catch(e){notice(`Impossible de publier : ${e.message}`,true)}}
  async function diagnostic(){const b=$('[data-action="diagnostic"]');b.disabled=true;$("#diagnostic-results").innerHTML='<p class="empty">Tests Discord en cours…</p>';try{const d=await json("/api/admin/discord-diagnostic",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({config:collect()})});$("#diag-bot").textContent=d.botConfigured?"Configuré":"Manquant";$("#diag-bot").className=d.botConfigured?"status-ok":"status-error";$("#diag-db").textContent=d.databaseConfigured?"Configurée":"Manquante";$("#diag-db").className=d.databaseConfigured?"status-ok":"status-error";$("#diag-duration").textContent=`${d.durationMs} ms`;const rows=[...d.servers.map(x=>({...x,kind:"Serveur"})),...d.channels.map(x=>({...x,kind:x.type==="forum"?"Forum":"Canal"}))];$("#diagnostic-results").innerHTML=rows.map(x=>`<div class="diagnostic-row"><div><strong>${esc(x.kind)} · ${esc(x.label)}</strong><small>${esc(x.discordName||x.id)}${x.readStatus?` · lecture ${esc(x.readStatus)}`:""}</small></div><span class="${x.ok?"status-ok":"status-error"}">${x.ok?"Opérationnel":`${esc(x.code||"Erreur")} · HTTP ${x.status||"—"}`}</span></div>`).join("")}catch(e){notice(`Diagnostic impossible : ${e.message}`,true)}finally{b.disabled=false}}
  async function addAdmin(){const id=$("#admin-id").value.trim();if(!validId(id))return notice("Entre un ID Discord valide de 17 à 20 chiffres.",true);try{await json("/api/admin/configuration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"add-admin",discordId:id})});$("#admin-id").value="";notice("Accès administrateur ajouté.");await load()}catch(e){notice(`Impossible d’ajouter cet accès : ${e.message}`,true)}}
  async function loadRoles(card){const guildKey=card.querySelector('[data-f="guildKey"]').value,guild=state.config.servers.find(s=>s.key===guildKey);if(!guild?.guildId)return;try{const d=await loadCatalog(guild.guildId);card.querySelector('[data-role-picker]').innerHTML=`<select data-role-choice><option value="">Ajouter un rôle…</option>${d.roles.filter(r=>!r.managed).map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join("")}</select>`}catch(e){notice(`Catalogue indisponible : ${e.message}`,true)}}
  document.addEventListener("click",async e=>{const tab=e.target.closest("[data-tab]");if(tab){$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===tab));$$('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===tab.dataset.tab));return}const action=e.target.closest("[data-action]")?.dataset.action;if(action==="save")return save();if(action==="reload"||action==="refresh")return load().catch(x=>notice(x.message,true));if(action==="add-admin")return addAdmin();if(action==="diagnostic")return diagnostic();if(action==="add-channel"){state.config=JSON.parse(JSON.stringify(state.config));state.config.liaison.channels.push({key:`liaison-${state.config.liaison.channels.length+1}`,label:"Nouvelle liaison",channelId:"",guildKey:state.config.servers[0]?.key||"cpd",type:"text",icon:"users",enabled:true,canRead:true,canWrite:true,canUpload:true,canMention:true,sortOrder:(state.config.liaison.channels.length+1)*10});renderLiaisons();dirty();return}const rm=e.target.closest("[data-remove-liaison]");if(rm){state.config=JSON.parse(JSON.stringify({...state.config,liaison:{...state.config.liaison,channels:state.config.liaison.channels.filter((_,i)=>i!==Number(rm.closest('[data-liaison]').dataset.liaison))}}));renderLiaisons();dirty();return}const rs=e.target.closest("[data-remove-server]");if(rs){const i=Number(rs.closest('[data-server]').dataset.server);state.config=JSON.parse(JSON.stringify(state.config));state.config.servers.splice(i,1);renderServers();renderLiaisons();renderAccess();dirty();return}const ra=e.target.closest("[data-remove-admin]");if(ra&&confirm("Révoquer cet accès administrateur ?")){try{await json("/api/admin/configuration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"remove-admin",discordId:ra.dataset.removeAdmin})});notice("Accès révoqué.");await load()}catch(x){notice(`Impossible de révoquer : ${x.message}`,true)}return}const rr=e.target.closest("[data-restore]");if(rr&&confirm("Restaurer cette version ? La version actuelle sera conservée.")){try{await json("/api/admin/configuration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"restore",historyId:rr.dataset.restore})});notice("Version restaurée.");await load()}catch(x){notice(`Restauration impossible : ${x.message}`,true)}return}const lr=e.target.closest("[data-load-roles]");if(lr)return loadRoles(lr.closest('[data-access]'));const rc=e.target.closest("[data-role-choice]");if(rc&&rc.value){const card=rc.closest('[data-access]'),box=card.querySelector('[data-f="roleIds"]');box.value=[...ids(box.value),rc.value].join("\n");rc.value="";dirty()}});
  document.addEventListener("input",e=>{if(e.target.closest(".tab"))dirty()});document.addEventListener("change",async e=>{if(e.target.matches('[data-f="guildKey"]')&&e.target.closest('[data-liaison]')){const card=e.target.closest('[data-liaison]'),f=card.querySelector('[data-f="channelId"]');try{const server=state.config.servers.find(s=>s.key===e.target.value);const d=await loadCatalog(server?.guildId);f.innerHTML=channelChoices({...state.config.liaison.channels[Number(card.dataset.liaison)],guildKey:e.target.value,channelId:""});if(d)dirty()}catch(x){notice(`Impossible de charger les salons : ${x.message}`,true)}}if(e.target.closest(".tab"))dirty()});
  load().catch(e=>notice(`Impossible de charger le panel : ${e.message}`,true));
})();
