(() => {
  const $ = selector => document.querySelector(selector);
  const $$ = selector => [...document.querySelectorAll(selector)];
  const esc = value => String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const validIds = value => [...new Set(String(value || "").split(/[\s,;]+/).filter(id => /^\d{17,20}$/.test(id)))];
  const slug = value => String(value || "").toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"").slice(0,40);
  const api = async (url, options = {}) => { const response = await fetch(url, { credentials:"same-origin", cache:"no-store", ...options }); const text = await response.text(); let data={}; try{data=text?JSON.parse(text):{};}catch{throw new Error(`Réponse serveur invalide (${response.status})`);} if(response.status===401)location.replace("/auth/login.html?error=login_required"); if(!response.ok||data.ok===false)throw Object.assign(new Error(data.code||`server_error_${response.status}`),{status:response.status,data}); return data; };
  let state=null, config=null, guilds=[], catalogs=new Map(), dirty=false, diagnostic=null;
  const viewTitles={overview:["ADMINISTRATION","Vue générale"],liaisons:["DISCORD","Liaisons Discord"],access:["SÉCURITÉ","Connexions & rôles"],admins:["SÉCURITÉ","Administrateurs"],diagnostic:["SURVEILLANCE","Diagnostic"],history:["AUDIT","Historique"]};

  function notify(message,error=false){const node=$("#alert");node.textContent=message;node.className=error?"error":"";node.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>node.hidden=true,6500);}
  function setDirty(value=true){dirty=value;$("#save-state").textContent=value?"Modifications non publiées":"Configuration synchronisée";$("#save-state").className=value?"error":"";renderPreview();}
  function guildOptions(selected){return guilds.map(g=>`<option value="${g.id}" ${g.id===selected?"selected":""}>${esc(g.name)}</option>`).join("");}
  function serverFor(key){return config.servers.find(s=>s.key===key)||config.servers[0];}
  function catalogForKey(key){return catalogs.get(serverFor(key)?.guildId)||{channels:[],roles:[]};}
  function serverKeyOptions(selected){return config.servers.map(s=>`<option value="${esc(s.key)}" ${s.key===selected?"selected":""}>${esc(s.label)}</option>`).join("");}
  function channelOptions(channel){const items=catalogForKey(channel.guildKey).channels||[];const currentExists=items.some(item=>item.id===channel.channelId);let html=currentExists?"":`<option value="${esc(channel.channelId)}" selected>Canal actuel · ${esc(channel.channelId)}</option>`;let category="";for(const item of items){if(item.category!==category){if(category)html+="</optgroup>";category=item.category;html+=`<optgroup label="${esc(category)}">`;}html+=`<option value="${item.id}" data-type="${item.type}" ${item.id===channel.channelId?"selected":""}>${item.type==="forum"?"▤":"#"} ${esc(item.name)}</option>`;}if(category)html+="</optgroup>";return html||'<option value="">Aucun salon accessible</option>';}
  function rolePicker(roles, selected, name){const set=new Set(selected||[]);return `<div class="role-picker" data-role-picker="${name}">${roles.filter(r=>!r.managed).map(role=>`<label><input type="checkbox" value="${role.id}" ${set.has(role.id)?"checked":""}><span>${esc(role.name)}</span></label>`).join("")||'<p class="empty">Aucun rôle chargé.</p>'}</div>`;}

  async function loadCatalog(guildId, fresh=false){if(!guildId)return;if(!fresh&&catalogs.has(guildId))return;const data=await api(`/api/admin/discord-catalog?guildId=${encodeURIComponent(guildId)}`);catalogs.set(guildId,{channels:data.channels||[],roles:data.roles||[]});}
  async function loadGuilds(fresh=false){const data=await api(`/api/admin/discord-catalog${fresh?"?refresh=1":""}`);guilds=data.guilds||[];$("#metric-guilds").textContent=String(guilds.length);}

  function renderServers(){$("#server-list").innerHTML=config.servers.map((server,index)=>`<div class="server-row" data-server="${index}"><label>Nom interne<input data-f="label" maxlength="80" value="${esc(server.label)}"></label><label>Serveur Discord<select data-f="guildId">${guildOptions(server.guildId)}</select></label><button class="mini danger" data-remove-server type="button" ${config.servers.length<2?"disabled":""}>Retirer</button><input data-f="key" type="hidden" value="${esc(server.key)}"></div>`).join("");}
  function renderLiaisons(){$("#liaison-list").innerHTML=config.liaison.channels.map((item,index)=>{const catalog=catalogForKey(item.guildKey);return `<article class="liaison-card" data-liaison="${index}"><div class="liaison-title"><div><span class="order-badge">${String(item.sortOrder).padStart(2,"0")}</span><strong>${esc(item.label)}</strong><small>${item.type==="forum"?"Forum":"Discussion"}</small></div><button class="mini danger" data-remove-liaison type="button">Retirer</button></div><div class="liaison-grid"><label class="field">Nom dans le MDT<input data-f="label" maxlength="90" value="${esc(item.label)}"></label><label class="field">Clé interne<input data-f="key" maxlength="40" value="${esc(item.key)}"></label><label class="field">Serveur<select data-f="guildKey" data-channel-guild>${serverKeyOptions(item.guildKey)}</select></label><label class="field">Ordre<input data-f="sortOrder" type="number" min="0" max="9999" value="${Number(item.sortOrder)||0}"></label><label class="field">Icône<select data-f="icon"><option value="inbox">Dossier</option><option value="radio">Radio</option><option value="users">Membres</option><option value="book">Document</option><option value="list">Liste</option></select></label><label class="field span-3">Salon ou forum Discord<select data-f="channelId">${channelOptions(item)}</select></label><label class="field">Usage<select data-f="type"><option value="text" ${item.type==="text"?"selected":""}>Discussion</option><option value="forum" ${item.type==="forum"?"selected":""}>Dépôts de plainte</option></select></label><div class="toggle-row"><label class="toggle"><input data-f="enabled" type="checkbox" ${item.enabled?"checked":""}>Visible</label><label class="toggle"><input data-f="canRead" type="checkbox" ${item.canRead?"checked":""}>Lecture</label><label class="toggle"><input data-f="canWrite" type="checkbox" ${item.canWrite?"checked":""}>Écriture</label><label class="toggle"><input data-f="canUpload" type="checkbox" ${item.canUpload?"checked":""}>Fichiers</label><label class="toggle"><input data-f="canMention" type="checkbox" ${item.canMention?"checked":""}>Mentions</label></div><div class="permission-box"><label class="field"><span>Rôles autorisés pour cette liaison</span>${rolePicker(catalog.roles,item.allowedRoleIds,"liaison")}</label><label class="field">Utilisateurs autorisés individuellement<textarea data-f="allowedUserIds" placeholder="Un ID Discord par ligne">${esc((item.allowedUserIds||[]).join("\n"))}</textarea><small>Laissez les deux zones vides pour autoriser tous les policiers connectés.</small></label></div></div></article>`}).join("")||'<p class="empty">Aucune liaison configurée.</p>';$$('[data-liaison]').forEach((card,index)=>card.querySelector('[data-f="icon"]').value=config.liaison.channels[index].icon||"users");}
  function renderAccess(){const labels={police:["Connexion policier","Accès au MDT via Discord et FiveM"],academy:["Police Academy","Accès au panel des instructeurs"]};$("#access-list").innerHTML=["police","academy"].map(key=>{const item=config.access[key],roles=catalogForKey(item.guildKey).roles;return `<article class="access-card" data-access="${key}"><div class="access-intro"><span>${key.toUpperCase()}</span><h3>${labels[key][0]}</h3><p>${labels[key][1]}</p></div><div><label class="field">Serveur contrôlé<select data-f="guildKey" data-access-guild>${serverKeyOptions(item.guildKey)}</select></label><label class="field">Condition<select data-f="mode"><option value="any" ${item.mode!=="all"?"selected":""}>Au moins un rôle</option><option value="all" ${item.mode==="all"?"selected":""}>Tous les rôles</option></select></label></div><div><span>Rôles autorisés</span>${rolePicker(roles,item.roleIds,"access")}<label class="field">Exceptions par ID utilisateur<textarea data-f="userIds">${esc((item.userIds||[]).join("\n"))}</textarea></label></div></article>`}).join("");}
  function renderAdmins(){const admins=state.administrators||[];$("#admin-list").innerHTML=admins.map(item=>`<article class="admin-row"><div><strong>${esc(item.displayName||item.discordId)} ${item.owner?'<span class="admin-owner">· Propriétaire</span>':''}</strong><small>${esc(item.discordId)}${item.addedByName?` · ajouté par ${esc(item.addedByName)}`:""}</small></div>${item.owner?'<span class="admin-owner">Accès permanent</span>':`<button class="mini danger" data-remove-admin="${item.discordId}" type="button">Retirer l’accès</button>`}</article>`).join("");$("#metric-admins").textContent=String(admins.length);const owner=admins.find(x=>x.owner);$("#owner-summary").innerHTML=owner?`<strong>${esc(owner.displayName)}</strong><small>${esc(owner.discordId)}</small>`:"<strong>Propriétaire non configuré</strong>";}
  function renderHistory(){const history=state.history||[];$("#history-list").innerHTML=history.map(item=>`<article class="history-row"><div><strong>Version ${item.version}</strong><small>${esc(item.summary||"Modification")} · ${esc(item.changedByName||"Système")} · ${new Date(item.createdAt).toLocaleString("fr-FR")}</small></div><button class="mini ghost" data-restore="${item.id}" type="button">Restaurer</button></article>`).join("")||'<p class="empty">Aucune ancienne version.</p>';}
  function renderPreview(){if(!config)return;let current=config;try{current=collect();}catch{}const channels=current.liaison.channels.slice().sort((a,b)=>a.sortOrder-b.sortOrder);$("#menu-preview").innerHTML=channels.map(item=>`<div class="${item.enabled?"":"off"}"><span>${esc(item.label||"Sans nom")}</span><small>${item.type==="forum"?"Forum":"Canal"} · ${item.sortOrder}</small></div>`).join("")||'<p class="empty">Aucune liaison.</p>';$("#metric-liaisons").textContent=String(channels.filter(x=>x.enabled).length);}
  function renderAll(){$("#admin-name").textContent=state.user?.displayName||"Administrateur";$("#version").textContent=String(state.meta?.version??"—");$("#updated-at").textContent=state.meta?.updatedAt?`${state.meta.updatedByName||"Administrateur"} · ${new Date(state.meta.updatedAt).toLocaleString("fr-FR")}`:"Configuration initiale";$("#liaison-section-label").value=config.liaison.sectionLabel;renderServers();renderLiaisons();renderAccess();renderAdmins();renderHistory();renderPreview();setDirty(false);}

  function selectedRoles(card){return [...card.querySelectorAll('[data-role-picker] input:checked')].map(input=>input.value);}
  function collect(){const servers=$$('[data-server]').map(card=>({key:slug(card.querySelector('[data-f="key"]').value)||`server-${Number(card.dataset.server)+1}`,label:card.querySelector('[data-f="label"]').value,guildId:card.querySelector('[data-f="guildId"]').value,enabled:true}));const access={...config.access};$$('[data-access]').forEach(card=>{const key=card.dataset.access;access[key]={...access[key],guildKey:card.querySelector('[data-f="guildKey"]').value,mode:card.querySelector('[data-f="mode"]').value,roleIds:selectedRoles(card),userIds:validIds(card.querySelector('[data-f="userIds"]').value)};});access.admin={label:"Administration configuration",guildKey:servers[0]?.key||"cpd",roleIds:[],userIds:[],mode:"any"};const channels=$$('[data-liaison]').map((card,index)=>{const val=name=>card.querySelector(`[data-f="${name}"]`);const channelId=val("channelId").value;const known=catalogForKey(val("guildKey").value).channels.find(x=>x.id===channelId);return{key:slug(val("key").value)||`liaison-${index+1}`,label:val("label").value,channelId,guildKey:val("guildKey").value,type:val("type").value||(known?.type||"text"),icon:val("icon").value,sortOrder:Number(val("sortOrder").value)||0,enabled:val("enabled").checked,canRead:val("canRead").checked,canWrite:val("canWrite").checked,canUpload:val("canUpload").checked,canMention:val("canMention").checked,allowedRoleIds:selectedRoles(card),allowedUserIds:validIds(val("allowedUserIds").value)};});return{servers,access,liaison:{sectionLabel:$("#liaison-section-label").value,channels}};}

  async function load(){document.body.classList.add("loading");try{state=await api("/api/admin/configuration");config=structuredClone(state.config);await loadGuilds();await Promise.all([...new Set(config.servers.map(s=>s.guildId))].map(id=>loadCatalog(id).catch(()=>{})));renderAll();}finally{document.body.classList.remove("loading");}}
  async function save(){const button=$("#save");button.disabled=true;try{const next=collect();const forumCount=next.liaison.channels.filter(x=>x.enabled&&x.type==="forum").length;if(forumCount!==1)throw new Error("Il faut exactement un forum actif pour les dépôts de plainte.");const data=await api("/api/admin/configuration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"save",config:next,summary:"Configuration publiée depuis le Control Center V2"})});notify("Configuration publiée et appliquée au MDT.");await load();}catch(error){notify(error.message,true);}finally{button.disabled=false;}}
  async function switchView(name){const [kicker,title]=viewTitles[name]||viewTitles.overview;$("#view-kicker").textContent=kicker;$("#view-title").textContent=title;$$('[data-view]').forEach(x=>x.classList.toggle("active",x.dataset.view===name));$$('[data-view-panel]').forEach(x=>{const active=x.dataset.viewPanel===name;x.hidden=!active;x.classList.toggle("active",active);});}
  async function refreshGuildData(){const button=$("#sync-guilds");button.disabled=true;try{catalogs.clear();await loadGuilds(true);await Promise.all([...new Set(config.servers.map(s=>s.guildId))].map(id=>loadCatalog(id,true).catch(()=>{})));renderServers();renderLiaisons();renderAccess();notify("Serveurs, salons et rôles Discord actualisés.");}catch(e){notify(e.message,true);}finally{button.disabled=false;}}
  async function diagnose(){const button=$("#run-diagnostic");button.disabled=true;$("#diagnostic-list").innerHTML='<p class="empty">Tests en cours…</p>';try{diagnostic=await api("/api/admin/discord-diagnostic",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({config:collect()})});$("#diag-bot").textContent=diagnostic.botConfigured?"Opérationnel":"Manquant";$("#diag-bot").className=diagnostic.botConfigured?"ok":"error";$("#diag-db").textContent=diagnostic.databaseConfigured?"Connectée":"Manquante";$("#diag-db").className=diagnostic.databaseConfigured?"ok":"error";$("#diag-time").textContent=`${diagnostic.durationMs} ms`;const rows=[...diagnostic.servers.map(x=>({...x,kind:"Serveur"})),...diagnostic.channels.map(x=>({...x,kind:x.type==="forum"?"Forum":"Canal"}))];$("#diagnostic-list").innerHTML=rows.map(x=>`<article class="diagnostic-row"><div><strong>${x.kind} · ${esc(x.label)}</strong><small>${esc(x.discordName||x.id)}${x.readStatus?` · lecture ${esc(x.readStatus)}`:""}</small></div><span class="${x.ok?"ok":"error"}">${x.ok?"Opérationnel":`${esc(x.code||"Erreur")} · HTTP ${x.status||"—"}`}</span></article>`).join("");$("#metric-health").textContent=rows.every(x=>x.ok)?"OK":`${rows.filter(x=>!x.ok).length} erreur(s)`;}catch(e){notify(e.message,true);}finally{button.disabled=false;}}
  async function addAdmin(){const id=$("#new-admin-id").value.trim();if(!/^\d{17,20}$/.test(id))return notify("L’ID Discord doit contenir entre 17 et 20 chiffres.",true);try{await api("/api/admin/configuration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"add-admin",discordId:id})});$("#new-admin-id").value="";notify("Administrateur ajouté.");await load();}catch(e){notify(e.message,true);}}

  document.addEventListener("input",e=>{if(e.target.closest('[data-liaison], [data-access], [data-server], .section-name'))setDirty();});
  document.addEventListener("change",async e=>{if(e.target.matches('[data-channel-guild], [data-access-guild]')){config=collect();const guildId=serverFor(e.target.value)?.guildId;await loadCatalog(guildId).catch(()=>{});renderLiaisons();renderAccess();setDirty();}else if(e.target.closest('[data-liaison], [data-access], [data-server]'))setDirty();});
  document.addEventListener("click",async e=>{const nav=e.target.closest('[data-view], [data-open-view]');if(nav){switchView(nav.dataset.view||nav.dataset.openView);return;}const removeL=e.target.closest('[data-remove-liaison]');if(removeL){config=collect();config.liaison.channels.splice(Number(removeL.closest('[data-liaison]').dataset.liaison),1);renderLiaisons();setDirty();return;}const removeS=e.target.closest('[data-remove-server]');if(removeS){config=collect();const removed=config.servers.splice(Number(removeS.closest('[data-server]').dataset.server),1)[0];config.liaison.channels.forEach(x=>{if(x.guildKey===removed.key)x.guildKey=config.servers[0].key});for(const key of ['police','academy'])if(config.access[key].guildKey===removed.key)config.access[key].guildKey=config.servers[0].key;renderServers();renderLiaisons();renderAccess();setDirty();return;}const removeA=e.target.closest('[data-remove-admin]');if(removeA&&confirm("Retirer l’accès à cet administrateur ?")){try{await api("/api/admin/configuration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"remove-admin",discordId:removeA.dataset.removeAdmin})});notify("Accès administrateur retiré.");await load();}catch(err){notify(err.message,true);}return;}const restore=e.target.closest('[data-restore]');if(restore&&confirm("Restaurer cette version ? La version actuelle restera disponible dans l’historique.")){try{await api("/api/admin/configuration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"restore",historyId:restore.dataset.restore})});notify("Configuration restaurée.");await load();}catch(err){notify(err.message,true);}}});
  $("#add-liaison").addEventListener("click",()=>{config=collect();config.liaison.channels.push({key:`liaison-${config.liaison.channels.length+1}`,label:"Nouvelle liaison",channelId:"",guildKey:config.servers[0]?.key||"cpd",type:"text",icon:"users",enabled:true,canRead:true,canWrite:true,canUpload:true,canMention:true,allowedRoleIds:[],allowedUserIds:[],sortOrder:(config.liaison.channels.length+1)*10});renderLiaisons();setDirty();});
  $("#add-server").addEventListener("click",()=>{config=collect();const unused=guilds.find(g=>!config.servers.some(s=>s.guildId===g.id));if(!unused)return notify("Tous les serveurs visibles par le bot sont déjà ajoutés.",true);config.servers.push({key:slug(unused.name)||`server-${config.servers.length+1}`,label:unused.name,guildId:unused.id,enabled:true});loadCatalog(unused.id).finally(()=>{renderServers();renderLiaisons();renderAccess();setDirty();});});
  $("#sync-guilds").addEventListener("click",refreshGuildData);$("#save").addEventListener("click",save);$("#discard").addEventListener("click",()=>{if(!dirty||confirm("Annuler les changements non publiés ?"))load().catch(e=>notify(e.message,true));});$("#run-diagnostic").addEventListener("click",diagnose);$("#add-admin").addEventListener("click",addAdmin);
  load().catch(error=>notify(error.message==="admin_owner_not_configured"?"Ajoute CPD_ADMIN_OWNER_ID dans les variables Vercel.":error.message,true));
})();
